---
jobs:
  test:
    name: Test
    uses: MattKobayashi/actions-workflows/.github/workflows/test.yaml@686b2644a231ae70f253b9e1f63e978cddfecad5 # v1.4.1
    with:
      app-container-name: irrd
      test-container-name: connection_test
      test-directory: tests
name: Test
on:
  pull_request:
    branches:
      - main
  workflow_dispatch:
permissions:
  contents: read
  pull-requests: write
